---
apiVersion: apikey.confluent.crossplane.io/v1alpha1
kind: APIKey
metadata:
  name: crossplane-test
  # annotations:
  #   crossplane.io/external-name: XXXXXXXXXXXXXXXXXXX
spec:
  # deletionPolicy: Delete
  forProvider:
    description: "crossplane-test0"
    resource: ${CONFLUENT_CLUSTER_ID}
    environment: ${CONFLUENT_ENVIRONMENT}
    serviceAccount: ${CONFLUENT_SERVICEACCOUNT}
  writeConnectionSecretToRef:
    name: confluent-apikey
    namespace: default
  providerConfigRef:
    name: confluent-provider