name: Provider confluent CI PR

on:
  pull_request:
    branches:
      - main      

env:
  BUILD_REGISTRY: dfdsdk
  TESTING_CI: "true"

jobs:
  ci:
    name: CI for PR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.17'
      - name: prereqs for make
        run: make submodules
      - name: lint
        run: make lint
      - name: prereqs for test
        run: go mod vendor
      - name: install confluent cli
        run: curl -sL --http1.1 https://cnfl.io/cli | sh -s -- -b $HOME/.local/bin v2.4.0
      - name: add confluent cli to path
        run: echo "$HOME/.local/bin" >> $GITHUB_PATH
      - name: test
        run: ./scripts/test.sh
      - name: build
        run: make build nolint=1
